---
# tasks file for phpmyadmin
- name: Install mariadb
  yum:
    name:
      - mariadb
      - mariadb-server
    state: latest

- name: Start mariadb
  service:
    name: mariadb
    enabled: true
    state: started

  notify:
    - Restart mariadb
